services:
  app:
    image: tomcat:10.1-jdk21
    container_name: gestor-series-app
    ports:
      - "8080:8080"
    volumes:
      - ./target/gestor-series-plataformes-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestor_series
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: gestor-series-db
    environment:
      - POSTGRES_DB=gestor_series
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
    